module.exports = {
  Apigw: require('./modules/apigw'),
  Cdn: require('./modules/cdn'),
  Cns: require('./modules/cns'),
  Cos: require('./modules/cos'),
  Domain: require('./modules/domain'),
  MultiApigw: require('./modules/multi-apigw'),
  MultiScf: require('./modules/multi-scf'),
  Scf: require('./modules/scf'),
  Tag: require('./modules/tag'),
  Postgresql: require('./modules/postgresql'),
  Vpc: require('./modules/vpc'),
  Cam: require('./modules/cam'),
  Metrics: require('./modules/metrics'),
  Layer: require('./modules/layer'),
  Cfs: require('./modules/cfs'),
  Cynosdb: require('./modules/cynosdb'),
};
