name: IntegrationTest

on:
  pull_request:
    branches: [master]
  push:
    paths:
      - 'src/**'

jobs:
  IntegrationTest:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Ensure connection with 'master' branch
          fetch-depth: 2

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      - name: Retrieve dependencies from cache
        id: cacheNpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: npm-v14-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-v14-${{ runner.os }}-${{ github.ref }}-
            npm-v14-${{ runner.os }}-refs/heads/master-

      - name: Install dependencies
        if: steps.cacheNpm.outputs.cache-hit != 'true'
        run: |
          npm update --no-save
          npm update --save-dev --no-save
      - name: Running integration tests
        run: npm run test
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID}}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY}}
          TENCENT_UIN: ${{ secrets.TENCENT_UIN}}
          TENCENT_APP_ID: ${{ secrets.TENCENT_APP_ID}}
          BUCKET: ${{ secrets.BUCKET}}
          DOMAIN: ${{ secrets.DOMAIN}}
          SUB_DOMAIN: ${{ secrets.SUB_DOMAIN}}
          REGION: ${{ secrets.REGION}}
          ZONE: ${{ secrets.ZONE}}
          VPC_ID: ${{ secrets.VPC_ID}}
          SUBNET_ID: ${{ secrets.SUBNET_ID}}
          CFS_VPC_ID: ${{ secrets.CFS_VPC_ID}}
          CFS_SUBNET_ID: ${{ secrets.CFS_SUBNET_ID}}
